[project]
name = "licence-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "customtkinter>=5.2.2",
    "nuitka>=2.6.9",
]
